### ISSUE TITLE
Can't talk to 'equiva' device

### ISSUE THREAD

**Issue by tinloaf** [rytilahti/python-eq3bt#10]
Hi,

I have an equiva thermostat (this: http://www.eq-3.com/products/eqiva/bluetooth-smart-radiator-thermostat.html) and I'm trying to communicate with it. I'm seeing the very same error as #5 - but I'm using python3.4. Here is a backtrace:

```
tinloaf@janeway ~ $ eq3cli --mac 00:1A:22:09:DE:DE --debug
DEBUG:eq3bt.eq3btsmart:Querying the device..
DEBUG:eq3bt.connection:Trying to connect to 00:1A:22:09:DE:DE
DEBUG:eq3bt.connection:Connected to 00:1A:22:09:DE:DE
DEBUG:eq3bt.connection:Writing b'0311090a15251f' to 1041 with with_response=True
DEBUG:eq3bt.connection:Waiting for notifications for 1
Traceback (most recent call last):
  File "/home/tinloaf/.virtualenvs/hass/bin/eq3cli", line 11, in <module>
    sys.exit(cli())
  File "/home/tinloaf/.virtualenvs/hass/lib64/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/tinloaf/.virtualenvs/hass/lib64/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/tinloaf/.virtualenvs/hass/lib64/python3.4/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/tinloaf/.virtualenvs/hass/lib64/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tinloaf/.virtualenvs/hass/lib64/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/tinloaf/.virtualenvs/hass/lib64/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/tinloaf/.virtualenvs/hass/lib64/python3.4/site-packages/eq3bt/eq3cli.py", line 38, in cli
    ctx.invoke(state)
  File "/home/tinloaf/.virtualenvs/hass/lib64/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/tinloaf/.virtualenvs/hass/lib64/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/tinloaf/.virtualenvs/hass/lib64/python3.4/site-packages/eq3bt/eq3cli.py", line 160, in state
    click.echo(dev)
  File "/home/tinloaf/.virtualenvs/hass/lib64/python3.4/site-packages/click/utils.py", line 221, in echo
    message = text_type(message)
  File "/home/tinloaf/.virtualenvs/hass/lib64/python3.4/site-packages/eq3bt/eq3btsmart.py", line 97, in __str__
    self.mode_readable,
  File "/home/tinloaf/.virtualenvs/hass/lib64/python3.4/site-packages/eq3bt/eq3btsmart.py", line 265, in mode_readable
    if mode.MANUAL:
AttributeError: 'NoneType' object has no attribute 'MANUAL'
```

I'm also very certain that the device is not currently 'connected' - I just restarted my bluetooth subsystem as well as the thermostat itself. Also, it seems to establish the connection and write some data, but then something is going wrong. Is there any way I can debug this further?

Thanks for any assistance,

Lukas

**Comment by tinloaf** [comment]
Oh - forget it. The thermostat seems not so speak bluetooth (or at least not whatever this library expects) as long as it's not attached to the radiator and didn't have its calibration.

**Comment by rytilahti** [comment]
It apparently still gets some sort of response. You could try to add some debug logging to see what it is receiving, but I'm not sure if it is worth the time :-)
