### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'MANUAL'

### ISSUE THREAD

**Issue by jempo** [rytilahti/python-eq3bt#29]
I've this problem when i connect to my EQ3. I'm running the latest version 0.1.10 in Homeassistant Env.

`
Traceback (most recent call last):
  File "/srv/homeassistant/bin/eq3cli", line 10, in <module>
    sys.exit(cli())
  File "/srv/homeassistant/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/srv/homeassistant/lib/python3.5/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/srv/homeassistant/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/homeassistant/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/eq3bt/eq3cli.py", line 38, in cli
    ctx.invoke(state)
  File "/srv/homeassistant/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/eq3bt/eq3cli.py", line 160, in state
    click.echo(dev)
  File "/srv/homeassistant/lib/python3.5/site-packages/click/utils.py", line 222, in echo
    message = text_type(message)
  File "/srv/homeassistant/lib/python3.5/site-packages/eq3bt/eq3btsmart.py", line 97, in __str__
    self.mode_readable,
  File "/srv/homeassistant/lib/python3.5/site-packages/eq3bt/eq3btsmart.py", line 265, in mode_readable
    if mode.MANUAL:
AttributeError: 'NoneType' object has no attribute 'MANUAL'
`

**Comment by rytilahti** [comment]
The tool could have nicer error reporting when it cannot establish the connection or fails to read data from the device.

**Comment by kinvaris** [comment]
I'm having the exact same issue. But for me the app still works and I am still able to connect via the Cli.

**Comment by ropperto** [comment]
Hello,
after upgrading the firmware via calor app I can't connect anymore to the thermostat and get the error:
_AttributeError: 'NoneType' object has no attribute 'MANUAL'_
The app still works fine.
