### ISSUE TITLE
BleakDBusError: Operation failed with ATT error: 0x0e (Connection Rejected

### ISSUE THREAD

**Issue by wieluk** [rytilahti/python-eq3bt#56]
Hey there not sure what is happening with the new release 0.2. I tried it because I use eq3 on home assistant.
```
pi@VpnPi:~ $ eq3cli
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/eq3bt/bleakconnection.py", line 106, in make_request
    with self:
  File "/home/pi/.local/lib/python3.9/site-packages/eq3bt/bleakconnection.py", line 65, in __enter__
    self._loop.run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.9/site-packages/bleak/backends/bluezdbus/client.py", line 931, in start_no                                                     tify
    assert_reply(reply)
  File "/home/pi/.local/lib/python3.9/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_rep                                                     ly
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Connection Rejected                                                      Due To Security Reasons)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/bin/eq3cli", line 8, in <module>
    sys.exit(cli())
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/eq3bt/eq3cli.py", line 47, in cli
    thermostat.update()
  File "/home/pi/.local/lib/python3.9/site-packages/eq3bt/eq3btsmart.py", line 217, in update
    self._conn.make_request(PROP_WRITE_HANDLE, value)
  File "/home/pi/.local/lib/python3.9/site-packages/eq3bt/bleakconnection.py", line 123, in make_request
    raise BackendException("Exception on write using bleak") from ex
eq3bt.BackendException: Exception on write using bleak
```

Anyone knows what is happening here?

**Comment by rytilahti** [comment]
Did it work previously / does it work with other backends? You can try to use `--backend` option to select either bluepy or gattlib to see if that helps.

If it didn't work previously, maybe your thermostat is running a firmware that requires pairing like discussed in the readme?

**Comment by wieluk** [comment]
I thing I paired my devices but it is long ago so I am not 100% sure.
but with bluepy it works. Do I have to install bleak separately?

```
pi@VpnPi:~ $ eq3cli --mac ... --backend bluepy
[...] Target 16.0 (mode: manual (16.0C) dst, away: no)
Locked: False
Batter low: False
Window open: False
Window open temp: 5.0
Window open time: 0:00:00
Boost: False
Current target temp: 16.0
Current comfort temp: 22.0
Current eco temp: 17.0
Current temp offset: 1.5
Current mode: manual (16.0C) dst
Valve: 0
```

**Comment by rytilahti** [comment]
Huh, that's odd... You have bleak installed as the stacktrace contains hints to it, so there should be nothing else to do. That error message implies that the device is not accepting the connection, but I don't really know what could cause that especially if it's working with other backends..

**Comment by rytilahti** [comment]
@toalex77 that seems to be another issue, see #57

**Comment by wieluk** [comment]
Does anyone know what I can try?
the bleak-lescan command does work. But I want to use the eq3bt in homeassistant and unfortunately there only bleak works for now...

**Comment by TechHummel** [comment]
I have the same issue now 😢 
@wieluk Which version of bluez are you using?

```
dpkg --status bluez | grep '^Version:'
Version: 5.55-3.1
```

**Comment by wieluk** [comment]
Version: 5.55-3.1+rpt1
This is my version. I would like to get this back to working without downgrading homeassistant before heating season anything I can do?

**Comment by TechHummel** [comment]
Thanks! Maybe @rytilahti is using a different version?

You could setup a [MQTT Bridge](https://github.com/zewelor/bt-mqtt-gateway) for bluetooth!

**Comment by rytilahti** [comment]
I cannot recall if I was doing testing on my laptop (bluez 5.65-2) or on my raspbi (5.55-3.1+rpt1), but the "Connection rejected" error sounds like a permission issue. Unfortunately there are also other issues that relate to homeassistant support, so fixing the permission problem will not fix the underlying problem.

For the time being I'd also suggest using a mqtt bridge. I'm not currently able to find time to fix this issue properly, so in the event no one comes up with a proper solution it may take some time to get this fixed. I'm sorry for that :-(

**Comment by TechHummel** [comment]
Thanks for your answer! It's actually a [wrong error message](https://github.com/hbldh/bleak/issues/972) (or see [here](https://github.com/hbldh/bleak/discussions/949)).

I will try to test with 5.65. I was hoping I could support on this but it's difficult since I can't get it to work with bleak at all :(
