### ISSUE TITLE
Provide asyncio interface for homeassistant

### ISSUE THREAD

**Issue by rytilahti** [rytilahti/python-eq3bt#59]
It likely doesn't make sense to convert the whole library to use asyncio, but providing a separate homeassistant-friendly interface could be fairly straightforward to implement.

See https://github.com/home-assistant/developers.home-assistant/pull/1412 and https://github.com/home-assistant/developers.home-assistant/pull/1412#issuecomment-1194723457 for best practices.

**Comment by TechHummel** [comment]
I just read https://developers.home-assistant.io/docs/network_discovery/ but it is not 100% clear to me what is needed here.
Do I understand correctly that the `BLEDevice` instances need to be passed from homeassistant to the eq3bt library?

**Comment by TechHummel** [comment]
@rytilahti Friendly ping!

**Comment by rytilahti** [comment]
Hi @TechHummel, sorry for the delay and thanks for the remainder!

Yeah, my understanding is also that the way to handle this would be by passing the `BLEDevice` created by homeassistant to this library, use it for the update cycle, toss it, and re-do the same procedure on the next cycle. As that doesn't map nicely to the existing API (performing connect on `__enter__`), it might make sense to create a very lightweight pure-bleak, asyncio interface separate from the existing ones that wraps the synchronous thermostat.

I created previously https://github.com/home-assistant/core/pull/74864 to modernize the code base, but I'm currently occupied with other things so I have no time to look into that until very late autumn or so...

**Comment by TechHummel** [comment]
I am looking into this, but I am currently blocked https://github.com/hbldh/bleak/issues/946. Will let you know about any progress.

**Comment by antoniomolram** [comment]
Hi! I am hitting the same issue here.... I will start checking out this. Any progress on this?

**Comment by TechHummel** [comment]
Sadly not! Not sure what's causing the issue!

**Comment by antoniomolram** [comment]
do you have your implementation working on the latest homeassistant? it seems that they want that you don't use the BleakClient() directly, instead the BLEDevice(). I am quite new with the Bleak library too.

It seems that doings so, home assistant can handle multiple BLE python interfaces (what makes sense).

I can use your package as an standalone application (without Home assistant), but once that I integrate it I can't use the functionality, and now I am trying to learn how to debug it :)

**Comment by TechHummel** [comment]
No, I don't have a working implementation! I am considering just using a MQTT bridge though!

**Comment by antoniomolram** [comment]
mm, could me maybe a easier solution for the moment, but is quite unfortunate that after a home assistant update the things stopped working (my wife is quite piss off :P)

**Comment by kaymueller** [comment]
> mm, could me maybe a easier solution for the moment, but is quite unfortunate that after a home assistant update the things stopped working (my wife is quite piss off :P)

It's super easy to downgrade HA via the SSH Plugin, worked great for me at least. Tho it's of course only a temporary fix. Make a full backup and download it, before sending this command to your HA. 

`ha core update --version 2022.6.7`

cheers,
Kay

**Comment by batja84** [comment]
> `ha core update --version 2022.6.7`
> 
> Hope that helps to make your wife a bit happier again. ;-)

I don't have a wife, but thank you very much. I'm happy now. Outside ist cold and I need my thermostat working.

**Comment by antoniomolram** [comment]
I made the downgrade but then other things stop work as I wanted (specially the new zigbee stuff). I will check more in detail all this but time is limited... (wife again) xD

**Comment by HandHsince1920** [comment]
I am using Home Assistant now on a downgraded version (2022.6.7) and everything works as it should. However, with every every release I feel the dire consequence of not being able to access the new features and also a bad feeling creeping in due to staying on an outdated version. Our whole apartment works fine with these thermostats and they consume almost no batteries, we recharge once every 18 months. I am more than happy and would love to support any kind of kickstarter request if any of the previous developers would be happy to assigns some valuable time to it.

**Comment by ndurchx** [comment]
This is no solution, but as a temporary fix, I switched to an bt-mqtt bridge, to work with home-assistant. https://github.com/zewelor/bt-mqtt-gateway

**Comment by wjarka** [comment]
> This is no solution, but as a temporary fix, I switched to an bt-mqtt bridge, to work with home-assistant. https://github.com/zewelor/bt-mqtt-gateway

Is there a way to run this on Hassio OS or did you use a separate Pi / PC for hosting this?

**Comment by LXR85** [comment]
> > This is no solution, but as a temporary fix, I switched to an bt-mqtt bridge, to work with home-assistant. https://github.com/zewelor/bt-mqtt-gateway
> 
> Is there a way to run this on Hassio OS or did you use a separate Pi / PC for hosting this?

I have had the same issue and the same question.

**Comment by ndurchx** [comment]
> > > This is no solution, but as a temporary fix, I switched to an bt-mqtt bridge, to work with home-assistant. https://github.com/zewelor/bt-mqtt-gateway
> > 
> > 
> > Is there a way to run this on Hassio OS or did you use a separate Pi / PC for hosting this?
> 
> I have had the same issue and the same question.

It is hosted separately. For me it was just another VM, because my HA is also virtualized. It is a bit of a downside, but even if the HA integration is fixed, I will stay at the mqtt bridge. It is much faster, and pops out more usable data, like valve state.

**Comment by HandHsince1920** [comment]
> > > > This is no solution, but as a temporary fix, I switched to an bt-mqtt bridge, to work with home-assistant. https://github.com/zewelor/bt-mqtt-gateway
> > > 
> > > 
> > > Is there a way to run this on Hassio OS or did you use a separate Pi / PC for hosting this?
> > 
> > 
> > I have had the same issue and the same question.
> 
> It is hosted separately. For me it was just another VM, because my HA is also virtualized. It is a bit of a downside, but even if the HA integration is fixed, I will stay at the mqtt bridge. It is much faster, and pops out more usable data, like valve state.
> 
> Edit: seems like there is a HA addon version: https://github.com/FaserF/hassio-addons/tree/master/bt-mqtt-gateway

What I really liked about the  solution via an integration was that it does not create more dependencies in form of further VM's and addons. It came out of the box and worked. 🥇

**Comment by wjarka** [comment]
Btw, I was able to get the valve state from the original integration. Can look it up later if you are interested

**Comment by batja84** [comment]
> like valve state

I can get valve state via template.
<img width="418" alt="image" src="https://user-images.githubusercontent.com/70979021/191794324-ab3cf4f9-d473-427a-b168-fe16d2506e85.png">

**Comment by batja84** [comment]
Hello guys! Any good changes in 2022.9.7? My HACS integration is dead now "You need HA version 2022.8.0 or newer to use this integration.". And I understand further will come more and more problems with "obsolete" HA Core. It's annoying.

**Comment by HandHsince1920** [comment]
> I am using Home Assistant now on a downgraded version (2022.6.7) and everything works as it should. However, with every every release I feel the dire consequence of not being able to access the new features and also a bad feeling creeping in due to staying on an outdated version. Our whole apartment works fine with these thermostats and they consume almost no batteries, we recharge once every 18 months. I am more than happy and would love to support any kind of kickstarter request if any of the previous developers would be happy to assigns some valuable time to it.

Just realised that one can actually support developers directly via github!

**Comment by r-jordan** [comment]
Hi all,

Meanwhile the issue is not resolved I found a temporal solution with a bluetooth to mqtt gateway. I hope it can help someone. I had mqtt configured previously. But if you don't have mqtt configured you should install the Mosquitto add-on previously. Then do the following:
 

1. Set add-on repository on Home Assistant OS to https://github.com/faserf/hassio-addons
2. Add user bt-mqtt-gateway in Mosquitto add-on or in Home Assistant with a password
3. Install bt-mqtt-gateway and put the following into the file /share/bt-mqtt-gateway.yaml:

```
mqtt:
  host: 192.168.1.2
  port: 1883
  username: bt-mqtt-gateway
  password: ***
  client_id: bt-mqtt-gateway
  availability_topic: thermostat/lwt_topic

manager:
  sensor_config:
    topic: homeassistant
    retain: true
  topic_subscription:
    update_all:
      topic: homeassistant/status
      payload: online
  command_timeout: 35
  workers:
    thermostat:
      args:
        devices:
          device1: 00:1A:22:xx:xx:xx
          device2: 00:1A:22:xx:xx:xx
        topic_prefix: thermostat
      topic_subscription: thermostat/+/+/set
      update_interval: 90
```

4. Configure the devices with their mac addresses and start the add-on

Thanks to @faserf for the add-on development and to @zewelor for the bluetooth mqtt gateway development.

**Comment by wjarka** [comment]
I've been using the MQTT gateway and it works great. However, since HomeAssistant introduced Bluetooth Proxies, I would love to have EQ3 over BT Proxy. May want to try to debug myself.

**Comment by LXR85** [comment]
> Hi all,
> 
> Meanwhile the issue is not resolved I found a temporal solution with a bluetooth to mqtt gateway. I hope it can help someone. I had mqtt configured previously. But if you don't have mqtt configured you should install the Mosquitto add-on previously. Then do the following:
> 
> 1. Set add-on repository on Home Assistant OS to https://github.com/faserf/hassio-addons
> 2. Add user bt-mqtt-gateway in Mosquitto add-on or in Home Assistant with a password
> 3. Install bt-mqtt-gateway and put the following into the file /share/bt-mqtt-gateway.yaml:
> 
> ```
> mqtt:
>   host: 192.168.1.2
>   port: 1883
>   username: bt-mqtt-gateway
>   password: ***
>   client_id: bt-mqtt-gateway
>   availability_topic: thermostat/lwt_topic
> 
> manager:
>   sensor_config:
>     topic: homeassistant
>     retain: true
>   topic_subscription:
>     update_all:
>       topic: homeassistant/status
>       payload: online
>   command_timeout: 35
>   workers:
>     thermostat:
>       args:
>         devices:
>           device1: 00:1A:22:xx:xx:xx
>           device2: 00:1A:22:xx:xx:xx
>         topic_prefix: thermostat
>       topic_subscription: thermostat/+/+/set
>       update_interval: 90
> ```
> 
> 4. Configure the devices with their mac addresses and start the add-on
> 
> Thanks to @FaserF for the add-on development and to @zewelor for the bluetooth mqtt gateway development.

Stupid question, but where can I find the /share folder?

**Comment by andrei-micu-ro** [comment]
Hi all,
As more and more people tend to look at this (broken) integration due to winter coming, I wanted to share my quick alternative to fix this issue without much hassle or custom integrations (MQTT is known to require configuration and altering .py files is also fairly complex).
My take on this is simple: use 2 separate HASS instances (onw with latest version - the main one - and another using an older version - the remote one - which still allows the old bluez mechanism)
To do this, you should:
- Install a separate HASS (even HassOS) image
- Add the eq3btsmart integration to the remote (old version) HASS
- Install and configure the Remote Home Assistant on both instances
- Share the Climate devices from the remote HASS to the new HASS

It works, it simply works; the only problem is that you need separate hardware for the remote Hass, as you need BlueZ running on Host. I used an old RPi 3b+ for this and even allowed me to place it in the house so that it reaches via BT the required thermostats.

I consider this approach to be the easiest with almost no impact as you use a separate HW and it's really easy to "undo" once the eq3 (using Bleak) is updated - you just need to remove the auxiliary Remote HASS HW.

Hope this helps.
PS: I tried with different approaches before taking this approach (tried altering the eq3 integration to work with bleak - complicated and has many many dependencies; tried writing a custom Py component to work with Eq3 Thermostats - too many flows and use-cases to be handled; also tried replacing the old py files (that work with BlueZ) in the latest HASS codebase - too many errors due to Core dependencies on Bleak)
The MQTT approach works well, however I found it to be fairly unstable and I had to constantly debug it

**Comment by dbuezas** [comment]
I have good news and bad news.

### Bad news

I know barely anything about custom integrations, bluetooth, asyncio and python, so there is no way I can send a meaningful PR. Particularly because my changes break CLI usage, and it also requires changes on the Home Assistant's component too.

### Good news

I managed to hack something together
<img width="593" alt="image" src="https://user-images.githubusercontent.com/777196/195823063-ba9533dd-9b4e-4fd5-83ea-6d4320f80032.png">

It still has some issues, so I'll try to fix them in the coming days. I hope somebody with more knowledge than me will eventually do it the proper way :) but in the mean time, I will make a temporary custom_component installable through HACS in the next 1 to two weeks.

**Comment by dbuezas** [comment]
Here you can find the HACS custom component.

https://github.com/dbuezas/eq3btsmart

I added some extra stuff like:
* Bluetooth autodiscovery
* Add via config flow
* BTProxies support (just using the correct APIs)
* retries
* ported everything to async
* fixed setting operation mode
* allowed to turn off by setting temp to 4.5°
* fetching schedules in HA
* (future) setting schedules via HA

<img width="283" alt="image" src="https://user-images.githubusercontent.com/777196/196235248-4024b4d7-be3a-4cae-960f-a8fbbe789549.png">
<img width="369" alt="image" src="https://user-images.githubusercontent.com/777196/196235917-2fb2ba4b-b3a8-4599-a01f-b5fe1fb9efea.png">

<img width="498" alt="image" src="https://user-images.githubusercontent.com/777196/196235809-6ff8b4d3-1efb-4dad-810a-20907651a3cb.png">

My Apologies to @rytilahti for going this way instead of making a PR, I left my reasons in the readme (mostly that the changes I made were too many, and they break the CLI and other backends)

**Comment by r-jordan** [comment]
Hi @dbuezas ,

Thank you!! I have got 3 of these valves and it's working for two of them but it's not connecting to one of the devices and the following errors are showing:

```
Logger: homeassistant.helpers.entity
Source: custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py:97
Integration: dbuezas EQ3 Bluetooth Smart Thermostats
First occurred: 18 d’octubre de 2022, a les 23:14:42 (114 occurrences)
Last logged: 01:30:03

Update for climate.eq3_salon2 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 718, in async_device_update
    await task
  File "/config/custom_components/dbuezas_eq3btsmart/climate.py", line 388, in async_update
    await self._async_thermostat_update()
  File "/config/custom_components/dbuezas_eq3btsmart/climate.py", line 381, in _async_thermostat_update
    await self._thermostat.async_update()
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/eq3btsmart.py", line 239, in async_update
    await self._conn.async_make_request(PROP_WRITE_HANDLE, value)
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 111, in async_make_request
    raise ex
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 97, in async_make_request
    await conn.start_notify(
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 546, in start_notify
    raise BleakError(f"Characteristic {char_specifier} not found!")
bleak.exc.BleakError: Characteristic 1056 not found!
```

I know the device is not the cause because it works ok with the bt-mqtt-gateway.

**Comment by dbuezas** [comment]
@r-jordan please raise an issue in the repo to avoid polluting this issue further :)

**Comment by andrei-micu-ro** [comment]
Just as a conclusion, the integration works very well, there are a few improvement areas but dbuezas is handling them like a pro !!
Managed to integrate one thermostat and it works better/faster than the original integration.
The only remaining problem is that it won't connect through ESPHome's bluetooth proxy due the thermostat (ver > 1.2) asking for PIN Pairing (currently not supported by ESP)

**Comment by rytilahti** [comment]
> My Apologies to @rytilahti for going this way instead of making a PR, I left my reasons in the readme (mostly that the changes I made were too many, and they break the CLI and other backends)

No worries, I have been maintaining this lib just in case someone is using it as I don't. I'm just glad that there's now a working solution for people who are using these devices in their homes! :-)

In case you want to make a push to make it into the homeassistant releases, it probably makes sense to create an async fork that removes all the cruft (we did similar for the tplink integration, pyhs100 -> python-kasa) and adjust the integration accordingly. I'm happy to help with the process if needed.

**Comment by batja84** [comment]
I have strange behavior one of my two thermostats. One of them is paired and working without problems with @dbuezas add-on, but another won't be paired via console. There is no message to input pair PIN.
 
<img width="496" alt="image" src="https://user-images.githubusercontent.com/70979021/197292608-3dee564b-3b58-4673-927f-700f80a80d0f.png">
<img width="320" alt="image" src="https://user-images.githubusercontent.com/70979021/197292638-8085967e-1406-4401-a374-90666d7ba758.png">
<img width="504" alt="image" src="https://user-images.githubusercontent.com/70979021/197292664-f8d72394-4a27-43b1-bdc7-4744c4b95b3b.png">
<img width="269" alt="image" src="https://user-images.githubusercontent.com/70979021/197292673-8658491b-7a5b-438f-8e8a-a130cb7dce42.png">
And this one working without problems.
![image](https://user-images.githubusercontent.com/70979021/197292755-06e10e55-b9f3-422a-a6b5-a6e74c7ce668.png)

**Comment by andrei-micu-ro** [comment]
For me usually worked some restarts:
- bluetooth service
- thermostat (batteries out)
It may be because it's stuck in a waiting loop. BlueZ did that when I used RPi.

I'm on a linux server now with a BT Dongle - way more stable, though it's using the same stack (BlueZ based).

Also as a quick hint, if it's just not asking for the Pin, try long-pressing the wheel to trigger the pairing mechanism in the Thermostat - maybe due to battery savings it doesn't trigger the pin when RPi asks for it.

**Comment by batja84** [comment]
> For me usually worked some restarts:
> 
> * bluetooth service
> * thermostat (batteries out)
>   It may be because it's stuck in a waiting loop. BlueZ did that when I used RPi.
> 
> I'm on a linux server now with a BT Dongle - way more stable, though it's using the same stack (BlueZ based).
> 
> Also as a quick hint, if it's just not asking for the Pin, try long-pressing the wheel to trigger the pairing mechanism in the Thermostat - maybe due to battery savings it doesn't trigger the pin when RPi asks for it.

Thanks for fast reply.
I have tried to take batteries out (for a minute o so) few times. 
I have pushed button to trigger pair-mode on the thermostat and tried to pair in console just after that.
RPi restart does nothing too. I have external BT dongle connected to RPi.

**Comment by andrei-micu-ro** [comment]
Sorry to hear that, I was expecting you to have tried all the normal stuff... 
Recently I fix pairing issues with 2 simple steps under bluetoothctl:
- remove 00:00:00:...
- pair 00:00:00:...
If in a few seconds after that it's not asking for Pin I press the wheel to trigger and usually works.

**Comment by jhass** [comment]
Keep trying to pair, it can take a long time in my experience. What also seemed to help sometimes was toggling the BLE setting in the long press menu settings a couple of times.

**Comment by batja84** [comment]
@jhass, @andrei-micu-ro 
I was ready to give up, but want to try one more time. I've disconnected BT dongle from RPi, than connected again. Pushed pair button and entered in console "pair mac" command. And it worked. 
<img width="502" alt="image" src="https://user-images.githubusercontent.com/70979021/197347021-61967be8-bf9d-4180-81be-e8d68d92c31a.png">
But now I'm not sure, that earlier it wasn't there, because by new connection I've got 2 full screen of messages and haven't read them all.
Thank you guys for your help!

**Comment by dbuezas** [comment]
I bought 7 for 20€ each last year, so I'll pass the thanks to @rytilahti for this repo :)

**Comment by HandHsince1920** [comment]
that is somehow funny, I never needed to pair anything with codes with the old integration even if I needed the pin on the app. To me the pin requirement appeared rather like a superficial layer of "security" that was not really deep rooted.

**Comment by HandHsince1920** [comment]
> Here you can find the HACS custom component.
> 
> https://github.com/dbuezas/eq3btsmart
> 
> I added some extra stuff like:
> 
>     * Bluetooth autodiscovery
> 
>     * Add via config flow
> 
>     * ~BTProxies support (just using the correct APIs)~ (probably only in firmware < 1.20)
> 
>     * retries
> 
>     * ported everything to async
> 
>     * fixed setting operation mode
> 
>     * allowed to turn off by setting temp to 4.5°
> 
>     * fetching schedules in HA
> 
>     * (future) setting schedules via HA
> 
> 
> <img alt="image" width="283" src="https://user-images.githubusercontent.com/777196/196235248-4024b4d7-be3a-4cae-960f-a8fbbe789549.png">
> 
> <img alt="image" width="369" src="https://user-images.githubusercontent.com/777196/196235917-2fb2ba4b-b3a8-4599-a01f-b5fe1fb9efea.png">
> 
> <img alt="image" width="498" src="https://user-images.githubusercontent.com/777196/196235809-6ff8b4d3-1efb-4dad-810a-20907651a3cb.png">
> 
> My Apologies to @rytilahti for going this way instead of making a PR, I left my reasons in the readme (mostly that the changes I made were too many, and they break the CLI and other backends)

that looks absolutely awesome. are you planning to get it into home assistant's normal releases? that would be great and due to your much improved autodiscovery it will certainly be of more use for less experiences users.

**Comment by dbuezas** [comment]
Thanks!
Yes, I'd wish to get it into home assistant core, but I'll wait until it ESPHome implements pairing. I will rhen probably ask @rytilahti for help reviewing my code (I'm not knowledgeable in Python)

**Comment by HandHsince1920** [comment]
> Thanks! Yes, I'd wish to get it into home assistant core, but I'll wait until it ESPHome implements pairing. I will rhen probably ask @rytilahti for help reviewing my code (I'm not knowledgeable in Python)

That would be really appreciated and also me the easiest option for many other users. Do you have a rough idea when the ESPHome pairing issue might be solved?

**Comment by LXR85** [comment]
Thank you @dbuezas for providing us with a workaround/solution, and thank you @andrei-micu-ro for the tip with removing the thermostat before pairing it! I have got now all 4 of my thermostats working:
![image](https://user-images.githubusercontent.com/6502056/200409043-36c791c8-2326-4827-9804-2a3f01695351.png)

One minor issue, however: When I change the temperature through Siri voice command (via HomeKit Bridge), the thermostat switches from OFF to Auto Mode and not to Manual Mode. Is this something you can fix, @dbuezas?

**Comment by dbuezas** [comment]
Yey!
But that issue with siri is very weird. Can you grab from the logs all commands set to the thermostat?
If there are a sequence of "set temp", then "set auto", then I could probably add an exception

**Comment by LXR85** [comment]
Yes, of course. I changed the thermostat (“Küche”) to 15 °C, the turned it off, and then back to 12 °C, all via Siri. This is the corresponding list of entries from the Logbook:

![image](https://user-images.githubusercontent.com/6502056/200424372-5129b2c8-7391-4cf6-8c36-d71497045120.png)

**Comment by LXR85** [comment]
Yes, that is indeed how it looks in the Home app:

<img src="https://user-images.githubusercontent.com/6502056/200566951-4970a90f-de00-46e9-bb92-0b131d9a5054.jpeg" width=33%>

**Comment by dbuezas** [comment]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/777196/202929482-d8c07fe5-cb5d-4fe3-ab42-57d60fd3db6b.png">

The custom EQ3 integration https://github.com/dbuezas/eq3btsmart  is now a proper device with the entities you missed, and then some more.

**Comment by HandHsince1920** [comment]
> <img alt="image" width="697" src="https://user-images.githubusercontent.com/777196/202929482-d8c07fe5-cb5d-4fe3-ab42-57d60fd3db6b.png">
> 
> The custom EQ3 integration https://github.com/dbuezas/eq3btsmart is now a proper device with the entities you missed, and then some more.

Wow, that looks awesome! Thanks for the great work. Do you know when it will be available via home assistant's own integrations section?

**Comment by dbuezas** [comment]
It may take a while, but eventually I'll do it. I want to add all features and polish it well before I attempt to publish the library and open a  PR to the core repo of home assistant.

**Comment by dbuezas** [comment]
![image](https://user-images.githubusercontent.com/777196/204043593-bc489b1e-9d66-473d-9271-e94077d82a00.png)
I think I'm finished with the features

**Comment by felixfischer** [comment]
@dbuezas David, thank you so much for putting in all the effort to keep this piece of hardware supported by Home Assistant! It is very much appreciated! <3

**Comment by wjarka** [comment]
Looks awesome! @dbuezas any news on the proxies?

**Comment by dbuezas** [comment]
Unfortunately no news on the BTProxy. 
I don't use them so somebody else should open an issue in EspHome. The issue is that EspHome cannot do pairing, and HA doesn't support pairing flows yet.
Note that even in older firmware where there is no real pin, pairing is still necessary
