### ISSUE TITLE
Can't connect to thermostat

### ISSUE THREAD

**Issue by fjfricke** [rytilahti/python-eq3bt#7]
#2 Always get the following message trying to connect to the thermostat. I'm new to the world of programming so please help me :) I'm using a Raspberry Pi 3. What am I doing wrong?

`pi@raspberrypi:~ $ eq3cli --mac 00:1A:22:08:29:FA
Traceback (most recent call last):
  File "/usr/local/bin/eq3cli", line 9, in <module>
    load_entry_point('python-eq3bt==0.1.5', 'console_scripts', 'eq3cli')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/eq3bt/eq3cli.py", line 27, in cli
    ctx.invoke(state)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/eq3bt/eq3cli.py", line 149, in state
    click.echo(dev)
  File "/usr/local/lib/python2.7/dist-packages/click/utils.py", line 221, in echo
    message = text_type(message)
  File "/usr/local/lib/python2.7/dist-packages/eq3bt/eq3btsmart.py", line 97, in __str__
    self.mode_readable,
  File "/usr/local/lib/python2.7/dist-packages/eq3bt/eq3btsmart.py", line 267, in mode_readable
    if mode.MANUAL:
AttributeError: 'NoneType' object has no attribute 'MANUAL'`

**Comment by fjfricke** [comment]
Ok I have solved the problem myself. I reinstalled python3 and reinstalled eq3bt with pip3 and now it works!

**Comment by rytilahti** [comment]
eq3cli should not allow execution anymore with python versions older than 3.4, good to hear it's working now though!
